### ISSUE TITLE
Remove compiled files from the repo (e.g. SharedItems/lib)

### ISSUE THREAD

**Issue by korydraughn** [dariusgrant/StellarVK#1]
Shared/Dynamic libraries and third party dependencies shouldn't be in the repo. Those should be provided through other means (e.g. the OS or possibly a package manager). Instead, document the dependencies for your library so that users know what they need to install.

**Comment by dariusgrant** [comment]
SharedItems/lib are no longer being used in this repo as it's focusing only on StellarVk library.
