### ISSUE TITLE
Template function always produces a copy of the argument

### ISSUE THREAD

**Issue by korydraughn** [dariusgrant/StellarVK#10]
https://github.com/dariusgrant/StellarVK/blob/422ab30213651f22c49f36fbc966706ccb6c9092/SharedItems/include/stellar_vk.hpp#L509

See this example for ways around avoiding copies: https://gcc.godbolt.org/z/E5j9WG

**Comment by dariusgrant** [comment]
I've used references for complex types for function parameters that don't require copies. Simple types such as uint32_t will still use copies as the compiler can perform optimizations.

**Comment by korydraughn** [comment]
In that case, I'd recommend constraining the range of types that this template accepts. If not, the extension map needs documentation explaining what can be passed.

**Comment by korydraughn** [comment]
However, if extension map is an implementation detail and users shouldn't be using it, It is fine and the implementation should be adjusted so that the extension map is not exposed.
