### ISSUE TITLE
Use constructors to enforce correct initialization

### ISSUE THREAD

**Issue by korydraughn** [dariusgrant/StellarVK#12]
If the data members are public, there is no need to provide setters.

Given that the data members are public, is it possible to get construction of the object wrong? If so, you could use a constructor to enforce correct initialization. You can also consider using the builder pattern to construct an object appropriately.
https://github.com/dariusgrant/StellarVK/blob/422ab30213651f22c49f36fbc966706ccb6c9092/SharedItems/include/stellar_vk.hpp#L563-L572

**Comment by dariusgrant** [comment]
The design I was going for was going to closely resemble how Vulkan's API is laid out. StellarVK is meant to be a convenient wrapper for Vulkan, which the same members that correspond to each other are public. The goal is to have provide a safer structure by mostly removing pointers and allowing the user to use containers. Below is a link to the Vulkan create info structure that the mentioned code is trying to alleviate. Let me know if you think my design is still flawed. 

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkInstanceCreateInfo.html

I do like the idea of the builder pattern after researching it a bit more. I was having trouble finding the difference between my implementation using method chaining but I do see the benefits it provide. I appreciate the advice.

**Comment by dariusgrant** [comment]
I've implemented the builder pattern for creating Vulkan related objects. Users will no longer be able to build an objects directly but instead must use the builder class associated with the object to ensure that it'll be constructed properly. This way, the data for the object is immutable after creation just as the corresponding Vulkan object would be after creation.
